apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        {{- if .Values.certManager.enabled }}
        - name: nifi-server-cert
          mountPath: "/etc/test-ebs/"
        {{- end }}
        - name: logs
          mountPath: "/etc/logs/"
      volumes:
      - name: testvolumes
        emptyDir: {}
      {{- if .Values.certManager.enabled }}
      - name: "nifi-server-cert"
        projected:
          sources:
          {{- range .Values.certManager.registryCertSecretNames }}
            - secret:
                name: {{ . | lower | quote }}
                items:
                  - key: tls.crt
                    path: {{ . | lower }}/tls.crt
                  - key: tls.key
                    path: {{ . | lower }}/tls.key
          {{- end }}
            - secret:
                name: nifi-keystore-and-truststore-password
                items:
                  - key: password
                    path: nifi-keystore-and-truststore-password/password
      {{- end }}
      - name: logs
        emptyDir: {}